name: EduPulse
description: An AI-powered educational app that enhances learning with notes
  summarization, MCQ generation, flashcards, and exam reminders.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3
  feather_icons: ^1.2.0
  file_picker: ^5.3.3
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  google_fonts: ^4.0.4
  google_generative_ai: ^0.4.6
  google_sign_in: ^6.1.4
  http: ^1.1.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  path_provider: ^2.1.0
  percent_indicator: ^4.2.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  supabase_flutter: ^1.10.7
  timeline_tile: ^2.0.0
  timezone: ^0.9.2
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

  workspace: any
flutter:
  uses-material-design: true

  assets:
    - assets/images/
